### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [aorek/mars-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by aorek** [comment]
Sorry for not tagging with WIP this repo. I'm actually working on this theme, it´s in an really early stage. When the theme is ready, I will glad to notify you.

**Comment by unixorn** [comment]
Ok, either add it as a PR to https://github.com/unixorn/awesome-zsh-plugins when you're done or create an issue there and I'll do it. Thanks!
